vim.g.mapleader = " "

vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.mouse = "a"
-- vim.opt.colorcolumn = "81"
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = false
vim.opt.foldcolumn = "auto"
vim.opt.scrolloff = 2
vim.opt.foldmethod = "expr"
vim.opt.foldenable = false
-- vim.opt.fillchars:append { diff = "╱" }
